server:
  port: 8081

spring:
#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"
  profiles:
    active: "default"
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}


  application:
    name: department
  datasource:
    url: jdbc:h2:mem:depdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  #    url:
#      jdbc:mysql://mysqldb:3306/test?useSSL=false&serverTimezone=UTC
#    username: root
#    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  cloud:
    config:
      enabled: true
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: "*"
build:
  version: "1.0"
author:
  name: "anas Department"
  email: "anaskhiari_Department@yahoo.com"